# Generated by Django 2.2.1 on 2019-06-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamma', '0002_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='accepted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
