# Generated by Django 2.2.1 on 2019-06-13 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamma', '0004_volunteer_experiences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='experiences',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_experiences', to='gamma.Skill'),
        ),
    ]
