# Generated by Django 2.2.1 on 2019-06-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamma', '0011_remove_volunteer_experiences'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='image',
            field=models.BinaryField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='image',
            field=models.BinaryField(default=None),
            preserve_default=False,
        ),
    ]
