# Generated by Django 2.2.1 on 2019-06-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamma', '0012_auto_20190613_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
