# Generated by Django 2.2.1 on 2019-06-13 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamma', '0013_auto_20190613_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charity',
            name='image',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='image',
        ),
    ]
