# Generated by Django 2.2.1 on 2019-06-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamma', '0015_volunteer_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charity',
            old_name='description',
            new_name='mission',
        ),
        migrations.AddField(
            model_name='charity',
            name='number',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='bio',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='image',
            field=models.ImageField(upload_to='images '),
        ),
    ]
