# Generated by Django 2.2.1 on 2019-06-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamma', '0016_auto_20190614_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='image',
            field=models.ImageField(default=None, upload_to='images '),
            preserve_default=False,
        ),
    ]
