# Generated by Django 2.2.1 on 2019-06-14 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamma', '0019_remove_charity_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='image',
        ),
    ]
