# Generated by Django 2.2.1 on 2019-06-15 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamma', '0020_remove_volunteer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='charity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamma.Charity'),
        ),
    ]
