# Generated by Django 2.2.1 on 2019-06-15 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamma', '0021_opportunity_charity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchedOpportunity',
        ),
    ]
