# Generated by Django 2.2.1 on 2019-06-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamma', '0022_delete_matchedopportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='cover_letter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
