# Generated by Django 2.2.1 on 2019-06-16 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamma', '0023_signup_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='experiences',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_experiences', to='gamma.Skill'),
        ),
    ]
