# Generated by Django 2.2.1 on 2019-06-16 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamma', '0024_volunteer_experiences'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
